name: Day 8 CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Run CI test
        run: |
          echo "CI is running"
          echo "Hello from GitHub Actions"

     - name: Validate enviroment
       run: |
         echo " Running on: "
         uname -a

     - name: Run basic checks
       run: |
         echo "CI checks passed"
